<span style='background:yellow'>**Question 1.1.**</span> In the next cell, assign the name `new_year` to the larger number among the following two numbers:

1. the **absolute value** of $2^{5}-2^{11}-2^1 + 1$, and 
2. $5 \times 13 \times 31 + 5$.

Try to use just one statement (one line of code).

Ans:

In [3]:
new_year = abs(2**5-2**11-2**1+1)
new_year

2017

In [4]:
new_year = abs((5*13*31)+5)
new_year

2020

<span style='background:yellow'>**Question 2.1.**</span> The module `math` also provides the name `e` for the base of the natural logarithm, which is roughly 2.71. Compute $e^{\pi}-\pi$, giving it the name `near_twenty`.

*Remember: You can access `pi` from the `math` module as well!*


Ans:

In [5]:
import math
#print(math.pi);
e = 2.718281828459045 
near_twenty = e**math.pi - math.pi
near_twenty

19.99909997918947

In [6]:
round(near_twenty, 8)

19.99909998

Question 2.1.1. A  𝜋4 -radian (45-degree) angle forms a right triangle with equal base and height, pictured below. If the hypotenuse (the radius of the circle in the picture) is 1, then the height is  sin(𝜋4) . Compute that value using sin and pi from the math module. Give the result the name sine_of_pi_over_four.

In [7]:
import math

sine_of_pi_over_four = math.sin(math.pi/4)

print(sine_of_pi_over_four)

0.7071067811865475


In [8]:
round(sine_of_pi_over_four, 8) == 0.70710678

True

<span style='background:yellow'>**Question 3.1.**</span> Use the method `show` to display the first 5 rows of `farmers_markets`. 

*Note:* The terms "method" and "function" are technically not the same thing, but for the purposes of this course, we will use them interchangeably.

**Hint:** `tbl.show(3)` will show the first 3 rows of `tbl`. Additionally, make sure not to call `.show()` without an argument, as this will crash your kernel!


In [9]:
from  google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
from datascience import * 
import pandas as pd
import matplotlib.pyplot as p 
farmers_markets = Table.read_table("/content/drive/My Drive/Colab Notebooks/farmers_markets.csv")
farmers_markets

FMID    | MarketName                                       | street                                                   | city       | County               | State                | zip   | x        | y       | Website                                               | Facebook                                                     | Twitter                             | Youtube | OtherMedia                                                   | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | updateTime            | Location                                                   | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time                                  | Season2Date | Season2Time | Season3Date | Season3Time | Season4Date | Season4Time
1012063 |  Caledonia Farmers Market Association - Danville | nan                                                      | Danville   | Caledonia            | Vermont              | 05828 | -72.1403 | 44.411  | https://sites.google.com/site/caledoniafarmersmarket/ | https://www.facebook.com/Danville.VT.Farmers.Market/         | nan                                 | nan     | nan                                                          | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | Y       | Y        | Y    | Y     | N    | Y      | Y     | Y      | N      | Y      | N         | Y       | N             | 6/28/2016 12:10:09 PM | nan                                                        | Y      | Y    | N       | Y     | N    | 06/08/2016 to 10/12/2016 | Wed: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
1011871 |  Stearns Homestead Farmers' Market               | 6975 Ridge Road                                          | Parma      | Cuyahoga             | Ohio                 | 44130 | -81.7286 | 41.3751 | http://Stearnshomestead.com                           | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | Y          | N      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | N       | N        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | Y       | N             | 4/9/2016 8:05:17 PM   | nan                                                        | Y      | Y    | N       | Y     | Y    | 06/25/2016 to 10/01/2016 | Sat: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
1011878 | 100 Mile Market                                  | 507 Harrison St                                          | Kalamazoo  | Kalamazoo            | Michigan             | 49007 | -85.5749 | 42.296  | http://www.pfcmarkets.com                             | https://www.facebook.com/100MileMarket/?fref=ts              | nan                                 | nan     | https://www.instagram.com/100milemarket/                     | N       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | N      | Y       | Y        | Y    | N     | Y    | N      | N     | Y      | Y      | N      | N         | N       | N             | 4/16/2016 12:37:56 PM | nan                                                        | Y      | Y    | N       | Y     | Y    | 05/04/2016 to 10/12/2016 | Wed: 3:00 PM-7:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
1009364 | 106 S. Main Street Farmers

In [11]:
farmers_markets.show(3)

<span style='background:yellow'>**Question 3.2.**</span> Use `num_columns` to find the number of columns in our farmers' markets dataset.

Assign the number of columns to `num_farmers_markets_columns`.


In [12]:
num_farmers_markets_columns= farmers_markets.num_columns
print("The table has", num_farmers_markets_columns, "columns in it!")

The table has 59 columns in it!


<span style='background:yellow'>**Question 3.3.**</span> Use `select` to create a table with only the name, city, state, latitude (`y`), and longitude (`x`) of each market.  Call that new table `farmers_markets_locations`.

*Hint:* Make sure to be exact when using column names with `select`; double-check capitalization!

In [13]:
farmers_markets_locations = farmers_markets.select('MarketName', 'State', 'city', 'x', 'y') 
print(farmers_markets_locations)

MarketName                                       | State                | city       | x        | y
 Caledonia Farmers Market Association - Danville | Vermont              | Danville   | -72.1403 | 44.411
 Stearns Homestead Farmers' Market               | Ohio                 | Parma      | -81.7286 | 41.3751
100 Mile Market                                  | Michigan             | Kalamazoo  | -85.5749 | 42.296
106 S. Main Street Farmers Market                | South Carolina       | Six Mile   | -82.8187 | 34.8042
10th Steet Community Farmers Market              | Missouri             | Lamar      | -94.2746 | 37.4956
112st Madison Avenue                             | New York             | New York   | -73.9493 | 40.7939
12 South Farmers Market                          | Tennessee            | Nashville  | -86.7907 | 36.1184
125th Street Fresh Connect Farmers' Market       | New York             | New York   | -73.9482 | 40.809
12th & Brandywine Urban Farm Market              | Dela

In [14]:
sorted(farmers_markets_locations.labels) == ['MarketName', 'State', 'city', 'x', 'y']

True

In [15]:
farmers_markets_locations.num_rows == 8546

True

<span style='background:yellow'>**Question 3.4.**</span> Suppose you just didn't want the `FMID` and `updateTime` columns in `farmers_markets`.  Create a table that's a copy of `farmers_markets` but doesn't include those columns.  Call that table `farmers_markets_without_fmid`.

In [16]:
farmers_markets_without_fmid = farmers_markets.drop("FMID","updateTime")
farmers_markets_without_fmid

MarketName                                       | street                                                   | city       | County               | State                | zip   | x        | y       | Website                                               | Facebook                                                     | Twitter                             | Youtube | OtherMedia                                                   | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | Location                                                   | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time                                  | Season2Date | Season2Time | Season3Date | Season3Time | Season4Date | Season4Time
 Caledonia Farmers Market Association - Danville | nan                                                      | Danville   | Caledonia            | Vermont              | 05828 | -72.1403 | 44.411  | https://sites.google.com/site/caledoniafarmersmarket/ | https://www.facebook.com/Danville.VT.Farmers.Market/         | nan                                 | nan     | nan                                                          | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | Y       | Y        | Y    | Y     | N    | Y      | Y     | Y      | N      | Y      | N         | Y       | N             | nan                                                        | Y      | Y    | N       | Y     | N    | 06/08/2016 to 10/12/2016 | Wed: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
 Stearns Homestead Farmers' Market               | 6975 Ridge Road                                          | Parma      | Cuyahoga             | Ohio                 | 44130 | -81.7286 | 41.3751 | http://Stearnshomestead.com                           | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | Y          | N      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | N       | N        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | Y       | N             | nan                                                        | Y      | Y    | N       | Y     | Y    | 06/25/2016 to 10/01/2016 | Sat: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
100 Mile Market                                  | 507 Harrison St                                          | Kalamazoo  | Kalamazoo            | Michigan             | 49007 | -85.5749 | 42.296  | http://www.pfcmarkets.com                             | https://www.facebook.com/100MileMarket/?fref=ts              | nan                                 | nan     | https://www.instagram.com/100milemarket/                     | N       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | N      | Y       | Y        | Y    | N     | Y    | N      | N     | Y      | Y      | N      | N         | N       | N             | nan                                                        | Y      | Y    | N       | Y     | Y    | 05/04/2016 to 10/12/2016 | Wed: 3:00 PM-7:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
106 S. Main Street Farmers Market                | 106 S. Main Street                                       | Six Mile   | nan                  | South Carolina       | 296

In [17]:
farmers_markets_without_fmid.num_columns == 57

True

In [18]:
print(sorted(farmers_markets_without_fmid.labels))

['Bakedgoods', 'Beans', 'Cheese', 'Coffee', 'County', 'Crafts', 'Credit', 'Eggs', 'Facebook', 'Flowers', 'Fruits', 'Grains', 'Herbs', 'Honey', 'Jams', 'Juices', 'Location', 'Maple', 'MarketName', 'Meat', 'Mushrooms', 'Nursery', 'Nuts', 'Organic', 'OtherMedia', 'PetFood', 'Plants', 'Poultry', 'Prepared', 'SFMNP', 'SNAP', 'Seafood', 'Season1Date', 'Season1Time', 'Season2Date', 'Season2Time', 'Season3Date', 'Season3Time', 'Season4Date', 'Season4Time', 'Soap', 'State', 'Tofu', 'Trees', 'Twitter', 'Vegetables', 'WIC', 'WICcash', 'Website', 'WildHarvested', 'Wine', 'Youtube', 'city', 'street', 'x', 'y', 'zip']


<span style='background:yellow'>**Question 3.5.**</span> Create a version of `farmers_markets_locations` that's sorted by **latitude (`y`)**, with the largest latitudes first.  Call it `farmers_markets_locations_by_latitude`.


In [19]:
farmers_markets_locations_by_latitude = farmers_markets
farmers_markets_locations_by_latitude.sort("y")


FMID    | MarketName                                  | street                                   | city                | County        | State          | zip   | x        | y       | Website                   | Facebook | Twitter | Youtube | OtherMedia | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | updateTime           | Location | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time                                | Season2Date | Season2Time | Season3Date | Season3Time | Season4Date | Season4Time
1004881 | Anne Heyliger Vegetable Market              | Queen Cross Street                       | Saint Croix         | Frederiksted  | Virgin Islands | nan   | -64.8799 | 17.7099 | nan                       | nan      | nan     | nan     | nan        | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                 | nan      | N      | N    | N       | N     | N    | nan                      | nan                                        | nan         | nan         | nan         | nan         | nan         | nan
1004880 | La Reine Farmers Market                     | Estate Body Slob                         | Saint Croix         | Christiansted | Virgin Islands | nan   | -64.7789 | 17.7322 | nan                       | nan      | nan     | nan     | nan        | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                 | nan      | N      | N    | N       | N     | N    | nan                      | nan                                        | nan         | nan         | nan         | nan         | nan         | nan
1004972 | Christian "Shan" Hendricks Vegetable Market | Company Street                           | Saint Croix         | Christiansted | Virgin Islands | nan   | -64.7043 | 17.7449 | nan                       | nan      | nan     | nan     | nan        | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                 | nan      | N      | N    | N       | N     | N    | nan                      | nan                                        | nan         | nan         | nan         | nan         | nan         | nan
1011612 | El Maercado Familiar                        | nan                                      | Arroyo zona urbana  | Arroyo        | Puerto Rico    | 00714 | -66.0617 | 17.9686 | nan                       | nan      | nan     | nan     | nan        | N       | N    | N          | Y      | N      | N       | N    | N       | Y     | Y          | Y     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | Y     | Y      | N      | N      | N         | N       | N             | 8/4/2015 10:54:40 AM | nan      | Y      | N    | Y       | Y     | N    | 01/01/2015 to 12/31/2015 | Fri: 7:00 AM-1:00 PM;Sat: 7:00 AM-1:00 PM; | nan         | nan         | nan         | nan         | nan         | nan
1011618 | El Mercado Familiar                         | nan                                      | Santa Isabel        | Santa Isabel  | Puerto Rico    | 00757 | -66.4184 | 17.9723 | http://agricultura.pr.gov | nan      | nan  

In [20]:
type(farmers_markets_locations_by_latitude) == tables.Table

True

In [21]:
list(farmers_markets_locations_by_latitude.column('y').take(range(3))) ==  [44.411012999999997, 41.375118000000001, 42.296024000000003]

True

<span style='background:yellow'>**Question 3.6.**</span> Use `california_farmers_markets` to create a table called `berkeley_markets` containing farmers' markets in Berkeley, California.

In [22]:
berkeley_markets = farmers_markets["city"]=="Berkeley"
berkeley_markets = farmers_markets.where("city","Berkeley")

In [23]:
berkeley_markets

FMID    | MarketName                        | street                                     | city     | County  | State      | zip   | x        | y       | Website                         | Facebook | Twitter                   | Youtube | OtherMedia | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | updateTime           | Location | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time            | Season2Date | Season2Time | Season3Date | Season3Time | Season4Date | Season4Time
1001026 | Downtown Berkeley Farmers' Market | Center Street & Martin Luther King Jr. Way | Berkeley | Alameda | California | 94704 | -122.273 | 37.8697 | http://ecologycenter.org/fm     | nan      | https://twitter.com/ecbfm | nan     | nan        | Y       | Y    | Y          | Y      | N      | Y       | Y    | Y       | Y     | Y          | Y     | Y    | N     | Y    | N       | Y    | Y      | Y       | Y        | Y    | Y     | N    | Y      | Y     | Y      | Y      | Y      | Y         | N       | Y             | 6/27/2016 1:48:35 PM | nan      | Y      | Y    | Y       | Y     | Y    | 01/01/2014 to 12/31/2014 | Sat: 10:00 AM-3:00 PM; | nan         | nan         | nan         | nan         | nan         | nan
1001025 | North Berkeley Farmers' Market    | Shattuck Ave. & Vine Street                | Berkeley | Alameda | California | 94709 | -122.269 | 37.8802 | http://www.ecologycenter.org/fm | nan      | https://twitter.com/ecbfm | nan     | nan        | Y       | Y    | Y          | Y      | N      | Y       | Y    | Y       | Y     | Y          | Y     | Y    | N     | Y    | N       | Y    | Y      | Y       | Y        | N    | N     | N    | N      | Y     | Y      | N      | Y      | N         | N       | N             | 6/27/2016 1:51:31 PM | nan      | Y      | Y    | Y       | Y     | Y    | 01/01/2016 to 12/31/2016 | Thu: 3:00 PM-7:00 PM;  | nan         | nan         | nan         | nan         | nan         | nan
1001242 | South Berkeley Farmers' Market    | Adeline Street at 63rd Street              | Berkeley | Alameda | California | 94703 | -122.272 | 37.8478 | http://www.ecologycenter.org/fm | nan      | https://twitter.com/ecbfm | nan     | nan        | Y       | Y    | Y          | Y      | N      | Y       | Y    | Y       | Y     | Y          | Y     | Y    | N     | Y    | N       | Y    | N      | Y       | Y        | N    | Y     | N    | N      | Y     | Y      | Y      | Y      | Y         | N       | N             | 6/27/2016 1:44:18 PM | nan      | Y      | Y    | Y       | Y     | Y    | 01/01/2016 to 12/31/2016 | Tue: 2:00 PM-6:30 PM;  | nan         | nan         | nan         | nan         | nan         | nan

In [24]:
berkeley_markets.num_rows == 3

True

In [25]:
list(berkeley_markets.column('city')) == ['Berkeley', 'Berkeley', 'Berkeley']

True

<span style='background:yellow'>**Question 4.1.1.**</span> Make an array containing the numbers 0, 1, -1, $\pi$, and $e$, in that order.  Name it `interesting_numbers`.  

*Hint:* How did you get the values $\pi$ and $e$ in lab 2?  You can refer to them in exactly the same way here.

In [26]:
import math
import numpy as np
interesting_numbers = np.array([0,1,-1, math.pi,math.e])
interesting_numbers

array([ 0.        ,  1.        , -1.        ,  3.14159265,  2.71828183])

In [27]:
type(interesting_numbers) == np.ndarray

True

In [28]:
len(interesting_numbers) == 5

True

In [29]:
all(interesting_numbers == np.array([0, 1, -1, math.pi, math.e]))

True

<span style='background:yellow'>**Question 4.1.2.**</span> Make an array containing the five strings `"Hello"`, `","`, `" "`, `"world"`, and `"!"`.  (The third one is a single space inside quotes.)  Name it `hello_world_components`.

*Note:* If you evaluate `hello_world_components`, you'll notice some extra information in addition to its contents: `dtype='<U5'`.  That's just NumPy's extremely cryptic way of saying that the data types in the array are strings.

In [30]:
hello_world_components = np.array(["Hello", ",", " ", "world", "!"])
hello_world_components

array(['Hello', ',', ' ', 'world', '!'],
      dtype='<U5')

In [31]:
type(hello_world_components) == np.ndarray

True

In [32]:
len(interesting_numbers) == 5

True

In [33]:
all(hello_world_components == np.array(["Hello", ",", " ", "world", "!"]))

True

<span style='background:yellow'>**Question 4.1.3.**</span> Import `numpy` as `np` and then use `np.arange` to create an array with the multiples of 99 from 0 up to (**and including**) 9999.  (So its elements are 0, 99, 198, 297, etc.)

In [34]:
multiples_of_99 = np.arange(start=0, stop=10000, step=99)
multiples_of_99

array([   0,   99,  198,  297,  396,  495,  594,  693,  792,  891,  990,
       1089, 1188, 1287, 1386, 1485, 1584, 1683, 1782, 1881, 1980, 2079,
       2178, 2277, 2376, 2475, 2574, 2673, 2772, 2871, 2970, 3069, 3168,
       3267, 3366, 3465, 3564, 3663, 3762, 3861, 3960, 4059, 4158, 4257,
       4356, 4455, 4554, 4653, 4752, 4851, 4950, 5049, 5148, 5247, 5346,
       5445, 5544, 5643, 5742, 5841, 5940, 6039, 6138, 6237, 6336, 6435,
       6534, 6633, 6732, 6831, 6930, 7029, 7128, 7227, 7326, 7425, 7524,
       7623, 7722, 7821, 7920, 8019, 8118, 8217, 8316, 8415, 8514, 8613,
       8712, 8811, 8910, 9009, 9108, 9207, 9306, 9405, 9504, 9603, 9702,
       9801, 9900, 9999])

In [35]:
type(multiples_of_99) == np.ndarray

True

In [36]:
len(multiples_of_99) == 102

True

In [37]:
all(multiples_of_99 == np.arange(0, 9999+99, 99))

True

<span style='background:yellow'>**Question 4.2.1.**</span> Set `population_1973` to the world population in 1973, by getting the appropriate element from `population_amounts` using `item`.


<span style='background:yellow'>**Question 4.3.1.**</span> Use `np.log10` to compute the logarithms of the world population in every year.  Give the result (an array of 66 numbers) the name `population_magnitudes`.  Your code should be very short.

In [38]:
from datascience import Table
population_amounts = Table.read_table("/content/drive/My Drive/Colab Notebooks/world_population.csv").column("Population")
population_amounts

array([2557628654, 2594939877, 2636772306, 2682053389, 2730228104,
       2782098943, 2835299673, 2891349717, 2948137248, 3000716593,
       3043001508, 3083966929, 3140093217, 3209827882, 3281201306,
       3350425793, 3420677923, 3490333715, 3562313822, 3637159050,
       3712697742, 3790326948, 3866568653, 3942096442, 4016608813,
       4089083233, 4160185010, 4232084578, 4304105753, 4379013942,
       4451362735, 4534410125, 4614566561, 4695736743, 4774569391,
       4856462699, 4940571232, 5027200492, 5114557167, 5201440110,
       5288955934, 5371585922, 5456136278, 5538268316, 5618682132,
       5699202985, 5779440593, 5857972543, 5935213248, 6012074922,
       6088571383, 6165219247, 6242016348, 6318590956, 6395699509,
       6473044732, 6551263534, 6629913759, 6709049780, 6788214394,
       6866332358, 6944055583, 7022349283, 7101027895, 7178722893,
       7256490011])

In [39]:
population_1973 = population_amounts.item(23)
population_1973

3942096442

In [40]:
# TEST
population_1973 == 3942096442

True

<span style='background:yellow'>**Question 4.3.2.**</span> Suppose the total charge at a restaurant is the original bill plus the tip. If the tip is 20%, that means we can multiply the original bill by 1.2 to get the total charge.  Compute the total charge for each bill in `restaurant_bills`, and assign the resulting array to `total_charges`.

In [41]:
restaurant_bills = np.array([20.12, 39.90, 31.01])
print("Restaurant bills:\t", restaurant_bills)

# Array multiplication
tips = 0.2 * restaurant_bills
print("Tips:\t\t\t", tips)

Restaurant bills:	 [ 20.12  39.9   31.01]
Tips:			 [ 4.024  7.98   6.202]


In [42]:
total_charges = 1.2 * restaurant_bills
total_charges

array([ 24.144,  47.88 ,  37.212])

In [43]:
type(total_charges) == np.ndarray

True

<span style='background:yellow'>**Question 4.3.3.**</span> The array `more_restaurant_bills` contains 100,000 bills!  Compute the total charge for each one.  How is your code different?

In [44]:
more_restaurant_bills = Table.read_table("/content/drive/My Drive/Colab Notebooks/more_restaurant_bills.csv").column("Bill")
more_restaurant_bills


array([ 16.87,  17.41,  10.18, ...,  16.09,  15.28,  29.72])

In [45]:
more_total_charges = 1.2 * more_restaurant_bills
more_total_charges

array([ 20.244,  20.892,  12.216, ...,  19.308,  18.336,  35.664])

In [46]:
type(more_total_charges) == np.ndarray

True

In [47]:
sum(abs(more_total_charges - 1.2 * more_restaurant_bills)) < 1e-6

True

<span style='background:yellow'>**Question 4.3.4.**</span> What was the sum of all the bills in `more_restaurant_bills`, *including tips*?

In [48]:
sum_of_bills = sum(more_total_charges)
sum_of_bills

1795730.0640000193

In [49]:
round(sum_of_bills, 2) == 1795730.06

True

<span style='background:yellow'>**Question 4.3.5.**</span> The powers of 2 ($2^0 = 1$, $2^1 = 2$, $2^2 = 4$, etc) arise frequently in computer science.  (For example, you may have noticed that storage on smartphones or USBs come in powers of 2, like 16 GB, 32 GB, or 64 GB.)  Use `np.arange` and the exponentiation operator `**` to compute the first 30 powers of 2, starting from `2^0`.

*Hint 1:* `np.arange(1, 2**30, 1)` creates an array with $2^{30}$ elements and **will crash your kernel**.

*Hint 2:* Part of your solution will involve `np.arange`, but your array shouldn't have more than 30 elements.

In [50]:
powers_of_2= 2**np.arange(30)
powers_of_2

array([        1,         2,         4,         8,        16,        32,
              64,       128,       256,       512,      1024,      2048,
            4096,      8192,     16384,     32768,     65536,    131072,
          262144,    524288,   1048576,   2097152,   4194304,   8388608,
        16777216,  33554432,  67108864, 134217728, 268435456, 536870912])

In [51]:
all(powers_of_2 == 2 ** np.arange(30))

True

<span style='background:yellow'>**Question 5.1.**</span> In the cell below, we've created 2 arrays. Using the steps above, assign `top_10_movies` to a table that has two columns called "Rating" and "Name", which hold `top_10_movie_ratings` and `top_10_movie_names` respectively.

In [52]:
top_10_movie_ratings = [9.2, 9.2, 9., 8.9, 8.9, 8.9, 8.9, 8.9, 8.9, 8.8]
top_10_movie_names = [
        'The Shawshank Redemption (1994)',
        'The Godfather (1972)',
        'The Godfather: Part II (1974)',
        'Pulp Fiction (1994)',
        "Schindler's List (1993)",
        'The Lord of the Rings: The Return of the King (2003)',
        '12 Angry Men (1957)',
        'The Dark Knight (2008)',
        'Il buono, il brutto, il cattivo (1966)',
        'The Lord of the Rings: The Fellowship of the Ring (2001)']
top_10_movies = Table().with_columns(
    "Rating", top_10_movie_ratings,
    "Name", top_10_movie_names
)
top_10_movies

Rating | Name
9.2    | The Shawshank Redemption (1994)
9.2    | The Godfather (1972)
9      | The Godfather: Part II (1974)
8.9    | Pulp Fiction (1994)
8.9    | Schindler's List (1993)
8.9    | The Lord of the Rings: The Return of the King (2003)
8.9    | 12 Angry Men (1957)
8.9    | The Dark Knight (2008)
8.9    | Il buono, il brutto, il cattivo (1966)
8.8    | The Lord of the Rings: The Fellowship of the Ring (2001)

In [53]:
from datascience import * 
type(top_10_movies) == tables.Table

True

In [54]:
top_10_movies.select('Rating', 'Name').sort('Name')

Rating | Name
8.9    | 12 Angry Men (1957)
8.9    | Il buono, il brutto, il cattivo (1966)
8.9    | Pulp Fiction (1994)
8.9    | Schindler's List (1993)
8.9    | The Dark Knight (2008)
9.2    | The Godfather (1972)
9      | The Godfather: Part II (1974)
8.8    | The Lord of the Rings: The Fellowship of the Ring (2001)
8.9    | The Lord of the Rings: The Return of the King (2003)
9.2    | The Shawshank Redemption (1994)

<span style='background:yellow'>**Question 5.2.**</span> `imdb.csv` contains a table of information about the 250 highest-rated movies on IMDb.  Load it as a table called `imdb`.

In [55]:
imdb = Table.read_table("/content/drive/My Drive/Colab Notebooks/imdb.csv")
imdb

Votes  | Rating | Title                 | Year | Decade
88355  | 8.4    | M                     | 1931 | 1930
132823 | 8.3    | Singin' in the Rain   | 1952 | 1950
74178  | 8.3    | All About Eve         | 1950 | 1950
635139 | 8.6    | Léon                  | 1994 | 1990
145514 | 8.2    | The Elephant Man      | 1980 | 1980
425461 | 8.3    | Full Metal Jacket     | 1987 | 1980
441174 | 8.1    | Gone Girl             | 2014 | 2010
850601 | 8.3    | Batman Begins         | 2005 | 2000
37664  | 8.2    | Judgment at Nuremberg | 1961 | 1960
46987  | 8      | Relatos salvajes      | 2014 | 2010
... (240 rows omitted)

In [56]:
type(imdb) == tables.Table

True

In [57]:
imdb.num_rows == 250

True

In [58]:
imdb.select('Votes', 'Rating', 'Title', 'Year', 'Decade').sort(0).take(range(2,5))

Votes | Rating | Title                       | Year | Decade
31003 | 8.1    | Le salaire de la peur       | 1953 | 1950
32385 | 8      | La battaglia di Algeri      | 1966 | 1960
35983 | 8.1    | The Best Years of Our Lives | 1946 | 1940