#Assignment four -part2

1) Write a Python (with NumPy) program to solve the system of linear
equations as following, print out the solution if it exists and print “no solution or infinite solution” for no solution/infinite solution:

 3x1 + x2 + 4 x3= 3

 9x1 + 4x2 +5 x3= 6

 9x1 + 4x2 +6 x3= 9

In [ ]:
import numpy as np

# Define the coefficients matrix A and the constant matrix b
A = np.array([[3, 1, 4], [9, 4, 5], [9, 4, 6]])
b = np.array([3, 6, 9])

# Find the determinant of A
det = np.linalg.det(A)

if det == 0:
    # If the determinant is zero, the system has either no solution or infinite solutions
    if np.array_equal(np.dot(A, b), np.zeros_like(b)):
        print("Infinite solutions")
    else:
        print("No solution")
else:
    # If the determinant is non-zero, the system has a unique solution
    x = np.linalg.solve(A, b)
    print("Solution:", x)


Solution: [-9. 18.  3.]


2.(30) Write a Python (with NumPy) program to center the data in each row in
matrix A

 A = [[2 4 6 8]  [6 6 8 8]]

In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[2, 4, 6, 8], [6, 6, 8, 8]])

# Compute the mean of each row
means = np.mean(A, axis=1)

# Subtract the means from each row
centered_A = A - means.reshape(-1, 1)

# Print the centered matrix
print("Centered A:\n", centered_A)


Centered A:
 [[-3. -1.  1.  3.]
 [-1. -1.  1.  1.]]


3.(50) Write a Python program to reduce the dimension of the data in matrix A
from 2x4 to 1x4 by using the PCA method. You may apply either linalg.eig() or
linalg.svd() in your program. Please output:

a. the covariance matrix

b. the eigenvalues of the covariance matrix

c. the eigenvectors of the covariance matrix

d. the first PC

e. the 1x4 reduced data matrix.

 A = [[2 4 6 8], [6 6 8 8]] 

In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[2, 4, 6, 8], [6, 6, 8, 8]])

# Compute the covariance matrix of A
cov = np.cov(A)

# Find the eigenvalues and eigenvectors of the covariance matrix
eigvals, eigvecs = np.linalg.eig(cov)

# Print the covariance matrix, eigenvalues, and eigenvectors
print("Covariance matrix:\n", cov)
print("Eigenvalues:\n", eigvals)
print("Eigenvectors:\n", eigvecs)

# Project the data onto the first principal component
reduced_A = np.dot(eigvecs[:, 0], A)

# Print the reduced data matrix
print("Reduced A:\n", reduced_A)


Covariance matrix:
 [[6.66666667 2.66666667]
 [2.66666667 1.33333333]]
Eigenvalues:
 [7.77123617 0.22876383]
Eigenvectors:
 [[ 0.92387953 -0.38268343]
 [ 0.38268343  0.92387953]]
Reduced A:
 [ 4.14385966  5.99161872  8.60474465 10.45250372]
